name: test-checkmarx-workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - prod

jobs:
  build:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
        with:
          ref: ${{ cloudbees.scm.branch }}
      - name: Run checkmarx
        uses: cloudbees-io/checkmarx
        with:
          serverURL: ${{ vars.CHECKMARX_SERVER_URL }}
          username: ${{ secrets.CHECKMARX_USERNAME }}
          password: ${{ secrets.CHECKMARX_PASSWORD }}
          token: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          language: "LANGUAGE_JAVA"