name: findsecbug-workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - prod

jobs:
  build:
    steps:
    - name: checkout-source-code
      uses: cloudbees-io/checkout@v1
    - name: Run findsecbug
      uses: cloudbees-io/findsecbugs
      with:
        language: "LANGUAGE_JAVA"