name: test-mendsca-workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
        with:
          ref: ${{ cloudbees.scm.branch }}
      - name: Run mendsca
        uses: cloudbees-io/mendsca@v1.0.1
        with:
          serverURL: ${{ vars.MENDSCA_SERVER_URL }}
          username: ${{ secrets.MENDSCA_USERNAME }}
          token: ${{ secrets.MEND_SECRET }}
          language: "LANGUAGE_JAVA"