name: test-sonarqube-workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - prod

jobs:
  build:
    steps:
    - name: checkout-source-code
      uses: cloudbees-io/checkout@v1
    - name: Run sonarqube action from platform.
      uses: cloudbees-io/sonarqube
      with:
        serverURL: "http://54.190.59.107:9000"
        username: "admin"
        password: ${{ secrets.SONARQUBE_PASSWORD }}
        language: "LANGUAGE_JAVA"