name: workflow-findsecbugs-mendsast-snyksca-jfrogxray-workflow
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - prod

jobs:
  build:
    steps:
    - name: checkout-source-code
      uses: cloudbees-io/checkout@v1
    - name: findsecbugs
      uses: cloudbees-io/findsecbug
      with:
        language: "LANGUAGE_JAVA"
    - name: mendsast
      uses: cloudbees-io/mendsast
      with:
        serverURL: ${{ vars.MENDSAST_SERVER_URL }}
        token: ${{ secrets.MENDSAST_CLIENT_TOKEN }}
        language: "LANGUAGE_JAVA"
    - name: snyksca
      uses: cloudbees-io/snyk-sca
      with:
        orgname: ${{ secrets.SNYK_SAAS_ORGNAME }}
        token: ${{ secrets.SNYK_SAAS_TOKEN }}
        language: "LANGUAGE_JAVA"
    - name: jfrog-xray
      uses: cloudbees-io/jfrog-xray
      with:
          registryURL: ${{ vars.JFROG_REGISTRY }}
          username: ${{ vars.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}
          image_location: "releaseiq01.jfrog.io/jfrog-test-local/alpine"
          image_tag: "latest"
          language: "LANGUAGE_JAVA"
